cuda:1
Namespace(withAug=True, AugDirect=20, method_name='Cheb', seed=100, IsDirectedData=True, dataset='cora_ml/', undirect_dataset='CiteSeer', MakeImbalance=True, CustomizeMask=False, K=2, heads=8, log_root='../logs/', log_path='test', data_path='../dataset/data/tmp/', epochs=1500, num_filter=2, p_q=0.95, p_inter=0.1, dropout=0.0, debug=False, new_setting=False, layer=2, lr=0.005, l2=0.0005, to_undirected=False, alpha=0.1, randomseed=-1, imb_ratio=100, n_layer=2, feat_dim=64, warmup=5, epoch=900, tau=2, max=False, no_mask=False, gdc='ppr')
excel_file_path is  TrueAug_Cheboutput.xlsx
dataset is  cora_ml
Traceback (most recent call last):
  File "/home/qj2004/magnet/src/GNNChangeTrainTest.py", line 515, in <module>
    main(args)
  File "/home/qj2004/magnet/src/GNNChangeTrainTest.py", line 53, in main
    dataset = load_directedData(args)
  File "/home/qj2004/magnet/src/utils/data_utils.py", line 45, in load_directedData
    dataset = citation_datasets(root='../dataset/data/tmp/cora_ml/cora_ml.npz')
  File "/home/qj2004/magnet/src/utils/Citation.py", line 40, in citation_datasets
    g = load_npz_dataset(root)
  File "/home/qj2004/magnet/src/utils/Citation.py", line 96, in load_npz_dataset
    with np.load(file_name, allow_pickle=True) as loader:
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../dataset/data/tmp/cora_ml/cora_ml.npz'
